context:
  version: "66.6.3"

package:
  name: unocss
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@unocss/cli/-/cli-${{ version }}.tgz
  sha256: c5aaa6a80fcdfc893cc37df26b5b0c72b48a2344f670462e002a26265dd34172

build:
  noarch: generic
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - esbuild
    - nodejs

tests:
  - script:
      - unocss --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The CLI for UnoCSS. A perfect fit for traditional backends.
  homepage: https://github.com/unocss/unocss
  repository: https://github.com/unocss/unocss

extra:
  recipe-maintainers:
    - danielnachun
