context:
  version: "66.9.2"

package:
  name: unocss
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@unocss/cli/-/cli-${{ version }}.tgz
  sha256: e04169e91176a93a7d468cd3acbadb482c2043abc20b6a4c7f95e5e17328ca78

build:
  noarch: generic
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - esbuild
    - nodejs

tests:
  - script:
      - unocss --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The CLI for UnoCSS. A perfect fit for traditional backends.
  homepage: https://github.com/unocss/unocss
  repository: https://github.com/unocss/unocss

extra:
  recipe-maintainers:
    - danielnachun
