context:
  version: "66.2.1"

package:
  name: unocss
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@unocss/cli/-/cli-${{ version }}.tgz
  sha256: 4ac4102948a6b6e01cc1b0156a18a088d49ca09d75b33c4a745cb8fb2aa81633

build:
  noarch: generic
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - esbuild
    - nodejs

tests:
  - script:
      - unocss --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The CLI for UnoCSS. A perfect fit for traditional backends.
  homepage: https://github.com/unocss/unocss
  repository: https://github.com/unocss/unocss

extra:
  recipe-maintainers:
    - danielnachun
