context:
  version: "66.5.9"

package:
  name: unocss
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@unocss/cli/-/cli-${{ version }}.tgz
  sha256: c55fb5837435bfc11080dd865245581af85502edefb15e99142a8c0a10173fc8

build:
  noarch: generic
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - esbuild
    - nodejs

tests:
  - script:
      - unocss --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The CLI for UnoCSS. A perfect fit for traditional backends.
  homepage: https://github.com/unocss/unocss
  repository: https://github.com/unocss/unocss

extra:
  recipe-maintainers:
    - danielnachun
