context:
  version: "66.10.0"

package:
  name: unocss
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@unocss/cli/-/cli-${{ version }}.tgz
  sha256: f025f13c22b7bf2141a8fa68a1a6203248ca5cbcad9b851a1e92486227566895

build:
  noarch: generic
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - esbuild
    - nodejs

tests:
  - script:
      - unocss --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The CLI for UnoCSS. A perfect fit for traditional backends.
  homepage: https://github.com/unocss/unocss
  repository: https://github.com/unocss/unocss

extra:
  recipe-maintainers:
    - danielnachun
